version: '3.8'
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./frontend/package.json:/app/package.json
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./.temp/frontend/node_modules:/app/node_modules
    command: |
      sh -c "
        if [ $INIT == true ]; then
          npm install --production=false
        fi
        npm start"
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/index.js:/app/index.js
      - ./.temp/backend/node_modules:/app/node_modules
    command: |
      sh -c "
        if [ $INIT == true ]; then
          npm install --production=false
        fi
        npm start"
