version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./package.json:/app/package.json
      - ./public:/app/public
      - ./src:/app/src
      - ./.temp/node_modules:/app/node_modules
    command: |
      sh -c "
        if [ $INIT == true ]; then
          npm install --production=false
        fi
        npm start"
