name: Build and Push Image

on:
  push:
    branches:
      - main
      - v[0-9]+

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Backend - build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.prod
          tags: xanmarta/watch2gether:latest
          secrets: GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
