name: Discord Push Notification
on: [push]
jobs:
  Create-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ github.event.head_commit.author.username }}
          DISCORD_AVATAR: "https://github.com/${{ github.event.head_commit.author.username }}.png"
          DISCORD_EMBEDS: >-
            [{
              "title": "A commit has been pushed to ${{ env.GITHUB_REF_NAME }}",
              "url": "${{ github.event.head_commit.url }}",
              "description": "**Author:** ${{ github.event.head_commit.author.username }} \n**ID:** ${{ github.event.head_commit.id }} \n**Message:** \n```\n${{ github.event.head_commit.message }} ``` \n**Added:** \n```\n${{ join(github.event.head_commit.added, '\n') }} ``` \n**Removed:** \n```\n${{ join(github.event.head_commit.removed, '\n') }} ``` \n**Modified:** \n```\n${{ join(github.event.head_commit.modified, '\n') }} ```",
              "color": "1127128",
              "footer": {
                "text": "${{ github.event.head_commit.timestamp }}"
              }
            }]
