name: Discord Push Notification
on: [push]
jobs:
  Create-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          embed: |
            {
              "title": "A commit has been pushed to $GITHUB_REF", 
              "description": "Author: {{ github.event.head_commit.author.name }}",
              "url": "{{ github.event.head_commit.url }}",
              "author": "{{ github.event.head_commit.author.username }}" 
            }
