name: Discord Push Notification
on: [push]
jobs:
  Create-Notification:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch changed files
        uses: tj-actions/changed-files@v18.7
        id: changed
        with:
          separator: '\n'

      - name: Get random color
        id: color_id
        run: echo "::set-output name=color::$(printf '%d%d%d' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))"

      - name: Manipulate commit message
        id: message_id
        run: echo "::set-output name=message::${{ github.event.head_commit.message }}"

      - name: Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ github.event.head_commit.author.username }}
          DISCORD_AVATAR: "https://github.com/${{ github.event.head_commit.author.username }}.png"
          DISCORD_EMBEDS: >-
            [{
              "title": "A commit has been pushed to ${{ github.ref }}",
              "url": "${{ github.event.head_commit.url }}",
              "description": "**Author:** ${{ github.event.head_commit.author.username }} \n**ID:** ${{ github.event.head_commit.id }} \n**Message:** \n```\n${{ steps.message_id.outputs.message }} ``` \n**Added:** \n```\n${{ steps.changed.outputs.added_files }} ``` \n**Modified:** \n```\n${{ steps.changed.outputs.modified_files }} ``` \n**Deleted:** \n```\n${{ steps.changed.outputs.deleted_files }} ```",
              "color": "${{ steps.color_id.outputs.color }}",
              "footer": {
                "text": "${{ github.event.head_commit.timestamp }}",
                "icon_url": "https://github.com/${{ github.event.head_commit.author.username }}.png"
              }
            }]
