name: Discord Push Notification
on: [push]
jobs:
  Create-Notification:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch changed files
        uses: tj-actions/changed-files@v18.7
        id: changed
        with:
          separator: ','
      
      - name: Manipulate file list 1
        run: |
          echo "ADDED=[${{ steps.changed.outputs.added_files }}]" >> $GITHUB_ENV"
          echo "MODIFIED=[${{ steps.changed.outputs.modified_files }}]" >> $GITHUB_ENV"
          echo "DELETED=[${{ steps.changed.outputs.deleted_files }}]" >> $GITHUB_ENV"
      
      - name: Manipulate file list 2
        id: list
        run: |
          echo "::set-output name=added::${{ toJSON(env.ADDED) }}"
          echo "::set-output name=modified::${{ toJSON(env.MODIFIED) }}"
          echo "::set-output name=deleted::${{ toJSON(env.DELETED) }}"

      - name: Get random color
        id: color_id
        run: echo "::set-output name=color::$(printf '%d%d%d' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))"

      - name: Manipulate commit message
        id: message_id
        run: echo "::set-output name=message::${{ github.event.head_commit.message }}"

      - name: Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ github.event.head_commit.author.username }}
          DISCORD_AVATAR: "https://github.com/${{ github.event.head_commit.author.username }}.png"
          DISCORD_EMBEDS: >-
            [{
              "title": "A commit has been pushed to ${{ github.ref }}",
              "url": "${{ github.event.head_commit.url }}",
              "description": "**Author:** ${{ github.event.head_commit.author.username }} \n**ID:** ${{ github.event.head_commit.id }} \n**Message:** \n```\n${{ steps.message_id.outputs.message }} ``` \n**Added:** \n```\n${{ join(fromJSON(steps.list.outputs.added), '\n') }} ``` \n**Modified:** \n```\n${{ join(fromJSON(steps.list.outputs.modified), '\n') }} ``` \n**Deleted:** \n```\n${{ join(fromJSON(steps.list.outputs.deleted), '\n') }} ```",
              "color": "${{ steps.color_id.outputs.color }}",
              "footer": {
                "text": "${{ github.event.head_commit.timestamp }}",
                "icon_url": "https://github.com/${{ github.event.head_commit.author.username }}.png"
              }
            }]
