name: Discord Push Notification
on: [push]
jobs:
  Create-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch changed files
        id: fetch_id
        run: echo "::set-output name=fetch_id::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
      - name: Get random color
        id: color_id
        run: echo "::set-output name=color_id::$(printf '%d%d%d' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))"
      - name: Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ github.event.head_commit.author.username }}
          DISCORD_AVATAR: "https://github.com/${{ github.event.head_commit.author.username }}.png"
          DISCORD_EMBEDS: >-
            [{
              "title": "A commit has been pushed to ${{ github.ref }}",
              "url": "${{ github.event.head_commit.url }}",
              "description": "**Author:** ${{ github.event.head_commit.author.username }} \n**ID:** ${{ github.event.head_commit.id }} \n**Message:** \n```\n${{ github.event.head_commit.message }} ``` \n**Changed files:** \n```\n${{ join(steps.fetch_id.outputs.*, '\n') }} ```",
              "color": "${{ join(steps.color_id.outputs.*, '') }}",
              "footer": {
                "text": "${{ github.event.head_commit.timestamp }}",
                "icon_url": "https://github.com/${{ github.event.head_commit.author.username }}.png"
              }
            }]
