name: Pull request

on: pull_request

jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      
      - name: Install dependencies for testing
        run: npm ci
      
      - name: Testing
        run: npm test
  
  Discord-Notification:
    runs-on: ubuntu-latest
    steps:

    - name: Get random color
      id: color_id
      run: echo "::set-output name=color::$(printf '%d%d%d' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))"

    - name: Discord
      uses: Ilshidur/action-discord@master
      continue-on-error: true
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: ${{ github.event.pull_request.user.login }}
        DISCORD_AVATAR: "https://github.com/${{ github.event.pull_request.user.login }}.png"
        DISCORD_EMBEDS: >-
          [{
            "title": "A pull request has been created: ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}",
            "url": "${{ github.event.pull_request.html_url }}",
            "description": "**Author:** ${{ github.event.pull_request.user.login }} \n**Number:** ${{ github.event.pull_request.number }} \n**Head branch:** `${{ github.event.pull_request.head.ref }}` \n**Base branch:** `${{ github.event.pull_request.base.ref }}` \n**Title:** \n```\n${{ github.event.pull_request.title }} ``` \n**Commits:** ${{ github.event.pull_request.commits }} \n**Lines added:** ${{ github.event.pull_request.additions }} \n**Lines deleted:** ${{ github.event.pull_request.deletions }} \n**Files changed:** ${{ github.event.pull_request.changed_files }}",
            "color": "${{ steps.color_id.outputs.color }}",
            "footer": {
              "text": "${{ github.event.pull_request.created_at }}",
              "icon_url": "https://github.com/${{ github.event.pull_request.user.login }}.png"
            }
          }]
